# Generated by Django 5.2.14 on 2026-05-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(blank=True, default='1', max_length=20)),
                ('fecha_operacion', models.DateField(blank=True, null=True)),
                ('tipo_actividad', models.CharField(choices=[('empresas', 'Empresas'), ('construccion', 'Construcción')], default='empresas', max_length=20)),
                ('letra_binding_case', models.CharField(blank=True, max_length=15)),
                ('numero_sipe', models.CharField(blank=True, max_length=50)),
                ('numero_mainframe', models.CharField(blank=True, max_length=50)),
                ('nombre_establecimiento', models.CharField(max_length=180)),
                ('empleador_razon_social', models.CharField(max_length=180)),
                ('cedula_ruc', models.CharField(max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('representante_legal', models.CharField(blank=True, max_length=160)),
                ('tipo_cedula_representante', models.CharField(blank=True, choices=[('', 'Seleccione'), ('nacional', 'Nacional'), ('extranjera', 'Extranjera'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('cedula_representante', models.CharField(blank=True, max_length=80)),
                ('direccion_establecimiento', models.CharField(blank=True, max_length=220)),
                ('numero_entrevistados', models.PositiveIntegerField(blank=True, null=True)),
                ('monto_salarios', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
