# Generated by Django 5.2.14 on 2026-07-07 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_inactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planilla_operativo', to='gestion.inscripcion')),
            ],
            options={
                'verbose_name': 'planilla de operativo',
                'verbose_name_plural': 'planillas de operativos',
            },
        ),
    ]
