MODULOS_GESTION = [
    {
        "codigo": "1",
        "slug": "inscripcion",
        "nombre": "Inscripción",
        "descripcion": "Gestione las inscripciones del sistema.",
        "icono": "documento",
        "color": "azul",
    },
    {
        "codigo": "2",
        "slug": "morosidad",
        "nombre": "Morosidad",
        "descripcion": "Consulte y gestione la morosidad.",
        "icono": "calendario",
        "color": "verde",
    },
    {
        "codigo": "3",
        "slug": "reclamos",
        "nombre": "Reclamos",
        "descripcion": "Administre los reclamos registrados.",
        "icono": "alerta",
        "color": "naranja",
    },
    {
        "codigo": "4",
        "slug": "planillas-complementarias",
        "nombre": "Planillas complementarias",
        "descripcion": "Gestione las planillas complementarias.",
        "icono": "tabla",
        "color": "morado",
    },
    {
        "codigo": "5",
        "slug": "casos-juez-ejecutor",
        "nombre": "Casos del juez ejecutor",
        "descripcion": "Administre los casos del juez ejecutor.",
        "icono": "balanza",
        "color": "azul-claro",
    },
    {
        "codigo": "6",
        "slug": "cierre-inactividad",
        "nombre": "Cierre e inactividad",
        "descripcion": "Realice cierres e inactividades.",
        "icono": "candado",
        "color": "verde",
    },
    {
        "codigo": "7",
        "slug": "trabajo-oficina",
        "nombre": "Trabajo de oficina",
        "descripcion": "Gestione el trabajo de oficina.",
        "icono": "maletin",
        "color": "ambar",
    },
    {
        "codigo": "8",
        "slug": "operativos",
        "nombre": "Operativos",
        "descripcion": "Administre los operativos.",
        "icono": "engranaje",
        "color": "morado",
    },
    {
        "codigo": "9",
        "slug": "reactivacion",
        "nombre": "Reactivación",
        "descripcion": "Realice reactivaciones de registros.",
        "icono": "recargar",
        "color": "azul",
    },
    {
        "codigo": "C",
        "slug": "certificaciones",
        "nombre": "Certificaciones",
        "descripcion": "Gestione las certificaciones.",
        "icono": "medalla",
        "color": "verde",
    },
    {
        "codigo": "O",
        "slug": "otros",
        "nombre": "Otros",
        "subtitulo": "Citaciones, corrección",
        "descripcion": "Acceda a otras opciones del sistema.",
        "icono": "archivo",
        "color": "ambar",
    },
]
